version: "3"
services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: myPassword
      database__connection__database: ghost
    depends_on:
      - "database"
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
